### ISSUE TITLE
Require every file to have a language

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ricecooker#100]
I was trying to parse the `lang` field of a file in Kolibri - it was set to `"None"`, this is not terribly helpful. All files have a language associated with them that describes the language this content is in.

**Comment by ivanistheone** [comment]
Right now [only `license` is required and enforced when validating](https://github.com/learningequality/ricecooker/blob/master/ricecooker/classes/nodes.py#L378). Are you suggesting we add another validation rule to enforce all content items should have a `language`?

I think it could work going forward, but there are plenty of existing channels with no-lang so the frontend might still have to be smart and tread None as 'en' or walk up the content tree to look for a language...

**Comment by rtibbles** [comment]
The frontend will assume `"en"` for `"None"` for now, yup.

**Comment by ivanistheone** [comment]
Ricecooker now require language to be set on channel.

The enforced-language-for-every `ContentNode` logic is now on Studio (at export time).
