### ISSUE TITLE
Buried type error in exception case in sushi_bar_client

### ISSUE THREAD

**Issue by dragondave** [learningequality/ricecooker#134]
Whilst trying to get a ricecooker up and running, I hit a chain of issues which might be worth fixing.

https://github.com/learningequality/ricecooker/blob/fb625eca06b1e6f803c4a8f7d6c64c3183f1625d/ricecooker/sushi_bar_client.py#L91

assumes `.__config_logger()` returns two items. But it returns `None` if `.run_id` is falsey.

https://github.com/learningequality/ricecooker/blob/fb625eca06b1e6f803c4a8f7d6c64c3183f1625d/ricecooker/sushi_bar_client.py#L160-L162

`.run_id` is the return value of `.__create_channel_run`

https://github.com/learningequality/ricecooker/blob/fb625eca06b1e6f803c4a8f7d6c64c3183f1625d/ricecooker/sushi_bar_client.py#L89

which has a broad sweeping exception which will silence the exception and return None.

(The exception in this case was a 400 for the post  'https://sushibar.learningequality.org/api/channelruns' -- will dig deeper separately; suspect API key wrong.)

I suggest `.__create_channel_run` possibly shouldn't silence the exception at all since it's probably impossible to recover gracefully from, and it should just crash ASAP to avoid later type errors. (It might be useful elsewhere).

**Comment by dragondave** [comment]
[it would be useful to `print (request.text)`, then `raise` -- turns out `chef_name` was a mandatory field]

**Comment by dragondave** [comment]
The same logic possibly applies to `__get_chef_name`: the root cause appears to be the git remote URL not being set up (!)

**Comment by ivanistheone** [comment]
Looking into this now, and posting the logs of the error that occur when running a good chef outside a git repo:

```
Chef name: Command '['git', 'config', '--get', 'remote.origin.url']' returned non-zero exit status 1.
Error channel run: 400 Client Error: Bad Request for url: https://sushibar.learningequality.org/api/channelruns/
run_id: None
'NoneType' object is not iterable
Traceback (most recent call last):
  File "./chef.py", line 31, in <module>
    chef.main()
  File "/private/tmp/cheftest/venv/lib/python3.6/site-packages/ricecooker/chefs.py", line 293, in main
    self.run(args, options)
  File "/private/tmp/cheftest/venv/lib/python3.6/site-packages/ricecooker/chefs.py", line 284, in run
    uploadchannel_wrapper(self, args, options)
  File "/private/tmp/cheftest/venv/lib/python3.6/site-packages/ricecooker/commands.py", line 33, in uploadchannel_wrapper
    uploadchannel(chef, **args_and_options)
  File "/private/tmp/cheftest/venv/lib/python3.6/site-packages/ricecooker/commands.py", line 110, in uploadchannel
    config.SUSHI_BAR_CLIENT = SushiBarClient(channel, username, token)
  File "/private/tmp/cheftest/venv/lib/python3.6/site-packages/ricecooker/sushi_bar_client.py", line 91, in __init__
    self.log_ws, self.log_handler = self.__config_logger()
TypeError: 'NoneType' object is not iterable
```

Root cause as identified by Dave is the code that is supposed to generate `chef_name`, which I'll now fix to return a string which should make the POST to `/api/channelruns` succeed.

Separately, we'll make `__config_logger` return None, None tuple to avoid the "object is not iterable" error.
