### ISSUE TITLE
Double-printing logging 

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/ricecooker#136]
* ricecooker version: 0.6.10
* Python version: 3.5.3 (/data/sushi-chef-tessa/venv/bin/python)
* Operating System: GNU/Linux  Ubuntu 14.04.5 LTS

### Description

When running a chef on vader, everything seems to double-print, i.e., the logger lines appear twice.

**Comment by ivanistheone** [comment]
Should be fixed in https://github.com/learningequality/ricecooker/pull/247

**Comment by benjaoming** [comment]
Having tried some of the examples and some other chefs, I think this is fixed. Otherwise, it must be an issue in the chef.
