### ISSUE TITLE
Mandatory 'nomonitor' breaks souschef

### ISSUE THREAD

**Issue by dragondave** [learningequality/ricecooker#157]
* ricecooker version: 0.6.16 (was fine in .13, I think)
* Python version: 3.5.2
* Operating System: Ubuntu 16.04

### Description

I tried to run an existing souschef (https://github.com/learningequality/sushi-chef-artsedge) and after upgrading it gave a KeyError for 'nomonitor' on https://github.com/learningequality/ricecooker/blob/f75986ac2681b64dee74697eb2863c4db05cb30c/ricecooker/commands.py#L110

This leads to calling `.run` on a `SushiChef` instance to crash if no `nomonitor` attribute is provided.

### What I Did

I can work around this by adding `nomonitor=False` to the invocation -- this isn't ideal since every souschef file will need to be updated.

I recommend we change `kwargs['nomonitor']` to `kwargs.get('nomonitor')` which will return None (assuming that's acceptable behavior) or explicitly set a default value with `kwargs.get('nomonitor', True)` or similarly for False.

@ivanistheone -- pinging since you'll probably have the best idea what the default should be.

**Comment by dragondave** [comment]
(this was a fresh virtual environment with the new ricecooker, and lxml and requests_cache; I hit some other issues with my old virtual environment when I upgraded but I'm not too fussed if a clean install works well)

**Comment by ivanistheone** [comment]
This will be fixed in https://github.com/learningequality/ricecooker/pull/158

but generally shouldn't be using the `.run` method for calling a chef, but instead `.main` which takes care of all the cmd-args parsing and calls run.

See PR: https://github.com/learningequality/sushi-chef-artsedge/pulls
