### ISSUE TITLE
Create sushi chef for CK-12

### ISSUE THREAD

**Issue by jamalex** [learningequality/ricecooker#21]
Site: http://www.ck12.org/

@lauradanforth is scoping the relevant CK-12 content for inclusion in the VF launch.

I've been playing around with the CK-12 API. I'm going to post some notes in here, for our later reference.

**Comment by jamalex** [comment]
Get all descendants of a branch:
http://www.ck12.org/flx/browse/modality/artifact/MAT/all?pageSize=100

Get all direct children of a branch (seems like the world "children" doesn't matter; perhaps anything except "all" can go in there):
http://www.ck12.org/flx/browse/modality/artifact/MAT/children?pageSize=100



e.g. Finding Least Common Multiples (LCM)

Base page at: http://www.ck12.org/elementary-math-grade-3/Finding-Least-Common-Multiples-LCM-EM3/

Makes XHR request to:
	http://api-prod.ck12.org/flx/get/minimal/modalities/Finding-Least-Common-Multiples-LCM-EM3?pageSize=1000&pageNum=0

Video page at: http://www.ck12.org/elementary-math-grade-3/Finding-Least-Common-Multiples-LCM-EM3/enrichment/Finding-Least-Common-Multiples-LCM/
Exercise page at: http://www.ck12.org/elementary-math-grade-3/Finding-Least-Common-Multiples-LCM-EM3/asmtpractice/Finding-Least-Common-Multiples-LCM-EM3-Practice/

**Comment by intelliant01** [comment]
Hi @jayoshih @jamalex , Any work planned around this or any heads up on this available?
