### ISSUE TITLE
Truncated exception message: "{} must have one of the following"

### ISSUE THREAD

**Issue by dragondave** [learningequality/ricecooker#211]
* ricecooker version: 0.6.30
* Python version: 3.6.5
* Operating System: Linux

Trying to make a chef, but got an exception, but the output was truncated:

```
  File "/home/dragon/chef/py3k/lib/python3.6/site-packages/ricecooker/classes/files.py", line 357, in validate
    assert ext in self.allowed_formats, "{} must have one of the following"
AssertionError: {} must have one of the following
```

https://github.com/learningequality/ricecooker/blob/master/ricecooker/classes/files.py#L357 should insted use a multiline string rather than splitting the string into separate chunks.

**Comment by ivanistheone** [comment]
fixed in https://github.com/learningequality/ricecooker/commit/e983afa262b26ea3c6abbb2ae836eb6861f0a9cc
