### ISSUE TITLE
unable to use the customized request session for the downloader's read function

### ISSUE THREAD

**Issue by lyw07** [learningequality/ricecooker#215]
* ricecooker version: 0.6.31
* Python version: 3.7
* Operating System: OSX

### Description

In [this line of code](https://github.com/learningequality/ricecooker/blob/master/ricecooker/utils/downloader.py#L76), the session used here is still `DOWNLOAD_SESSION`, regardless of the `session` value passed in through the parameter.

### What I Did

pass in a customized session to the read function of downloader, and check that the session that makes the request is not the customized one.

**Comment by ivanistheone** [comment]
fixed in https://github.com/learningequality/ricecooker/commit/c2e4b2ba338f8612d456551d2189bac74b122015
