### ISSUE TITLE
provider, tags not assignable in __init__ on content nodes

### ISSUE THREAD

**Issue by dragondave** [learningequality/ricecooker#226]
* ricecooker version: 0.6.36
* Python version: 3.5
* Operating System: Ubuntu [Vader]

### Description

Attempted to pass "provider" when creating a new content node with create_node().
Failed: `create_node() got an unexpected keyword argument 'provider'`.
The documentation for the individual content node classes implies passing provider is valid.
Inspection of the code reveals `TreeNode`s can take a provider when created via `__init__`.
https://github.com/learningequality/ricecooker/blob/master/ricecooker/classes/nodes.py#L310

This also applies to 'tags'.

### Workaround

set `node.provider = "Provider Company"` after initialising the node.
Likewise: `node.tags = ['algebra', 'calculus']`

### Recommendation

Modify `ContentNode.__init__()` to permit provider attribute.
https://github.com/learningequality/ricecooker/blob/master/ricecooker/classes/nodes.py#L447

Check that validation is performed on it, etc.

**Comment by ivanistheone** [comment]
The provider and tags are handled by the ` **kwargs` on line 447 which then gets forwarded to TreeNode init on line 450.

I tested this and it worked:

```
from ricecooker.classes.nodes import TopicNode, VideoNode
TopicNode(source_id='fefe', title='Hello', provider='Someprovider', tags=['onetag'])
VideoNode(source_id='fefe', title='Hello', provider='Someprovider', tags=['onetag'], license='Public Domain')
```
