### ISSUE TITLE
Cannot use certain URLs for thumbnails

### ISSUE THREAD

**Issue by dragondave** [learningequality/ricecooker#227]
* ricecooker version: 0.6.36
* Python version: 3.5.3
* Operating System: Ubuntu (vader)

### Description

If you import a thumbnail via `HTML5AppNode(..., thumbnail='.jpg?itok=8gl2hL7q2')`; the thumbnail file is rejected, and the crawler crashes with a ricecooker.exceptions.InvalidNodeException: Invalid node (ThumbnailFile must have one of the following extensions: ['jpg', 'jpeg', 'png'].

This means that importing arbitary URLs isn't a reasonable approach; it should probably succeed (it is probably a jpg file after all) or fail non-fatally.
### What I Did
```
  File "/data/py35/lib/python3.5/site-packages/ricecooker/classes/nodes.py", line 195, in validate_tree
    assert child.validate_tree()
  File "/data/py35/lib/python3.5/site-packages/ricecooker/classes/nodes.py", line 193, in validate_tree
    self.validate()
  File "/data/py35/lib/python3.5/site-packages/ricecooker/classes/nodes.py", line 701, in validate
    raise InvalidNodeException("Invalid node ({}): {} - {}".format(ae.args[0], self.title, self.__dict__))
```

**Comment by ivanistheone** [comment]
This should be handled correctly now, see
https://github.com/learningequality/ricecooker/blob/master/tests/test_thumbnails.py#L72-L77

Trying to make all extension-extraction go through the function `extract_path_ext`:
https://github.com/learningequality/ricecooker/blob/master/ricecooker/classes/files.py#L42-L58
