### ISSUE TITLE
Crash if too-long provider string in log message.

### ISSUE THREAD

**Issue by dragondave** [learningequality/ricecooker#228]
* ricecooker version: 0.6.36
* Python version: 3.5
* Operating System: Linux 

### Description

A too-long "Provider" string crashes in config as the logger line saying it's been truncated fails due to MAX_CHAR_LIMITS not containing a provider entry.

Handle limit being none due to a missing entry and add a provider entry to MAX_CHAR_LIMITS.

https://github.com/learningequality/ricecooker/blob/master/ricecooker/config.py#L160

**Comment by ivanistheone** [comment]
@dragondave Please open a PR that the adds limits based on `MAX_AGGREGATOR_LENGTH` and `MAX_AGGREGATOR_LENGTH` to the [`MAX_CHAR_LIMITS`](https://github.com/learningequality/ricecooker/blob/master/ricecooker/config.py#L109) lookup.

I'll get that merged in ASAP

**Comment by ivanistheone** [comment]
fixed in https://github.com/learningequality/ricecooker/pull/229
