### ISSUE TITLE
Need validation for channel description length

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/ricecooker#235]
### Description

Need to do some channel-level validation.

### What I Did

Tried to upload a long description and ricecooker didn't stop me --- got an error from Studio:
<img width="992" alt="BUG no validation on channel description" src="https://user-images.githubusercontent.com/163966/71095703-0d890900-217b-11ea-8eda-c6ff262c4951.png">

**Comment by kollivier** [comment]
Putting in the next milestone as I consider validation fixes as part of the "docs + tutorials to get ricecooker ready for more contributors" project.

**Comment by ivanistheone** [comment]
Fixed here https://github.com/learningequality/ricecooker/commit/a246fe5d4371ab8a25e55445d9d474c6d47dbca0#diff-c7f133f8e73bff48aa135316e3e60d3cR191
