### ISSUE TITLE
H5P responsive image rendering issue

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/ricecooker#236]
### Description

Dynamically loaded image assets don't show up right because resize event doesn't happen.

Visit the [Virtual Tour (360)](http://35.185.120.102/en/learn/#/topics/c/70f4a245fbb75a68917780517f3c210f) node in the H5P Samples channel.

Alternatively you an open the [h5p root](http://35.185.120.102:9090/zipcontent/8b5005343cf885501e4dd2cfe960aaa0.h5p/) for that node.

Navigate to this page (and click the +) 

![before action](https://user-images.githubusercontent.com/163966/71277562-4663e200-2323-11ea-819d-b5838a2db903.png)

### Observed
![observed result](https://user-images.githubusercontent.com/163966/71277593-57acee80-2323-11ea-9625-d027eb155a0c.png)

The image file [exists](http://35.185.120.102:9090/zipcontent/8b5005343cf885501e4dd2cfe960aaa0.h5p/content/images/file-5c73b982c5a37.jpg) and is loaded correctly into the page but its height is very small so cannot see it since resize didn't happen.

You can see it if you play around with window size:
<img width="589" alt="Screen Shot 2019-12-20 at 12 24 27 PM" src="https://user-images.githubusercontent.com/163966/71277732-b2dee100-2323-11ea-9762-3fa6f8b94aed.png">

### Expected

The image to load and some js code to run to resize box height:
<img width="1234" alt="something is resizing this" src="https://user-images.githubusercontent.com/163966/71277657-7d39f800-2323-11ea-8350-d87ae183e6aa.png">

see the source website https://h5p.org/virtual-tour-360

### Comments

This could be a content issue or a H5P viewer plugin issue (why doesn't the image-loaded event not trigger the resize).

**Comment by rtibbles** [comment]
Fixed in https://github.com/learningequality/kolibri/pull/7989
