### ISSUE TITLE
tests/testcontent has files but is in .gitignore

### ISSUE THREAD

**Issue by kollivier** [learningequality/ricecooker#243]
### Description

While locally running tests for PR #213, I kept hitting thumbnail generation errors. Upon investigation, the problem was that some of the generated files I had in tests/testcontent were old versions, such as htmltest.zip, so their contents did not match what the test expected.

Since `tests/testcontent` was in `.gitignore`, I thought its content would be safe to delete, but after doing so I realized that directory had committed files in it, so I ended up wiping the directory and doing a git checkout.

Right now, there's no easy way for a person or a script to know which files can and should be deleted in that directory, and which are a part of the repo. 

To avoid confusion in the future, I think all files that are not committed to the repo should go to a separate directory, which will be created at test start and wiped at test completion. If we want to avoid the download step each time, we should consider either committing the files to the repo or utilizing requests caching for the downloads.

**Comment by ivanistheone** [comment]
Yeah the [`tests/testcontent`](https://github.com/learningequality/ricecooker/tree/master/tests/testcontent) could use some cleanup. 

Yes, let's add two subfolders `downloaded/` and `generated/` that are .gitignored and put all files in there that can be wiped.

> If we want to avoid the download step each time, we should consider either committing the files to the repo or utilizing requests caching for the downloads.

We definitely don't want to commit chunky videos/mp3 to the repo, and I'm not sure how it would work with requests caching. Do you mean requests-cache? I remember trying to use that for chefs and it didn't work very well.

What about adding a `make cleantests` command or something to wipe the `downloaded/` and `generated/` dirs?

**Comment by ivanistheone** [comment]
See https://github.com/learningequality/ricecooker/pull/245 for a fix for this.

If you have ideas for a wipe-downloaded-after-each-test-session, I'd like to hear but I'm pretty happy with the existing `make clean-test` command which can be used whenever we want to start from a clean slate.

**Comment by kollivier** [comment]
I think if we separate download and generated files out as you propose, then we can just leave downloaded files between test runs, ideally caching headers and comparing them to determine if anything changed. 

For generated files, I think we should wipe and re-run for each test run. If we don't want to do this, then ideally I think we should commit anything we don't want to re-generate each time unless it's a really large file.

A simpler option in the short term would be to modify `make test` so that, whenever it reports failures, it will also spit out a warning to run `make clean-test` first and try the tests again. Then update the `README.md` file to inform people they should run `make test` instead of running `pytest` directly.

**Comment by ivanistheone** [comment]
@kollivier Updated PR#245 to wipe generated on each run.

The `make test` also runs `clean-test` now (unconditionally).

**Comment by ivanistheone** [comment]
Fixed in #245
