### ISSUE TITLE
Default language and listing language

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ricecooker#261]
* ricecooker version: 0.6.42
* Python version: 3.6
* Operating System: Any

### Description

It's unclear from `ChannelNode` if `language` is the default language of nodes without a language or if it is the language that the channel is listed as.

Some channels are multilingual and relevant in several listings. This can be the case of channels for refugee camps or targeted for countries with several school languages - commonly, English is mixed with other languages.

It could be solved with two properties:

1) `ChannelNode.default_language`
2) `ChannelNode.listing_languages` - possible fallback: `[self.default_language]`
3) `ChannelNode.language`: Deprecated, is set to the value of `self.default_language`.

(Kolibri Studio has to support this as well)

**Comment by ivanistheone** [comment]
> It's unclear from ChannelNode if language is the default language of nodes without a language or if it is the language that the channel is listed as.

It is both for now, but see below for discoverability workaround.

------

> Some channels are multilingual [...]

In this case, set the language code to 'mul' (multiple languages), and set the topic and content node language codes inside the channel appropriately. See the `MultipleLanguagesChef` channel in the [docs/examples/langauges.html](https://ricecooker.readthedocs.io/en/latest/examples/languages.html)

------

> [...] and relevant in several listings. 

This is handled as a computation by Studio—in addition to the channel language, each channel has a computed field `included_languages` which contains the set of all language codes present within the channel.

**Comment by benjaoming** [comment]
@ivanistheone - the discoverability workaround can work for 0.6, but where do you track notes and issues to be implemented in future Ricecooker versions?

We chatted about the `language` property of ChannelNode / TopicNode / DocumentNode with respect to "inherit from parent" on Studio. This could be solved by raising a WARNING for empty `language` properties or with the parent or by always automatically using `language` from the parent rather than leaving it unset.
