### ISSUE TITLE
support "xml:base" attribute for resources on imsmanifest.xml

### ISSUE THREAD

**Issue by icarito** [learningequality/ricecooker#298]
* ricecooker version: trunk
* Python version: 3.8
* Operating System: GNU

### Description

I'm trying to import SCORM file from GeoGebra using the `imscp` library, using the example script.
The files in the manifest can't be found because they're expected to be found in a subdirectory which is declared in a `xml:base` attribute which points to the subdirectory where the resources can be found.

### What I Did

I downloaded https://www.geogebra.org/material/download/format/scorm/id/aac5vmhT which is a SCORM zip file from GeoGebra.
I renamed the file to eventos.zip and placed it in examples/ directory for imscp library.
I ran `educalab_chef.py` with modified metadata and a correct token, and got the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/icarito/Proyectos/imscp/examples/.ricecooker-temp/tmpnutmpflx/APIWrapper.js'
```
The file is actually present under the `/SCORM` subdirectory as is referenced in the imsmanifest.xml 's `resource` tag.

**Comment by kollivier** [comment]
@icarito I plan on looking into this, but one thing that I'm wondering about is that the temp path doesn't have the SCORM subdirectory in it. 

One other thing that might be worth trying is a different approach we've used for some SCORM content. We basically have a separate topic tree creation function in the imscp library called `make_topic_tree_with_entrypoints` that leaves the SCORM zip unmodified, but creates special endpoints that redirect to various tree items in the zip. You can see the function here:

https://github.com/learningequality/imscp/blob/cfbf165a2af009d0ce387737224696aa7d57b2a6/src/imscp/ricecooker_utils.py#L66

If you use this, I think it should avoid any issues with files missing from the end result. In addition to the args taken by `make_topic_tree`, you need to pass the path of the SCORM zip into the function, as well as set `temp_dir` (you can use `tempfile.tempdir` if you don't have a temp dir to set it to).

Please let me know if this helps!

**Comment by icarito** [comment]
> @icarito I plan on looking into this, but one thing that I'm wondering about is that the temp path doesn't have the SCORM subdirectory in it.

I just understood your doubt, the reason being that I had replaced "example.zip" with my SCORM file from https://www.geogebra.org/material/download/format/scorm/id/aac5vmhT - this .zip file does have a SCORM subdirectory in it (and references the files within it with the xml:base idiom on the `resource` tag.

> 
> One other thing that might be worth trying is a different approach we've used for some SCORM content. We basically have a separate topic tree creation function in the imscp library called `make_topic_tree_with_entrypoints` that leaves the SCORM zip unmodified, but creates special endpoints that redirect to various tree items in the zip. You can see the function here:
> 
> https://github.com/learningequality/imscp/blob/cfbf165a2af009d0ce387737224696aa7d57b2a6/src/imscp/ricecooker_utils.py#L66
> 
> If you use this, I think it should avoid any issues with files missing from the end result. In addition to the args taken by `make_topic_tree`, you need to pass the path of the SCORM zip into the function, as well as set `temp_dir` (you can use `tempfile.tempdir` if you don't have a temp dir to set it to).
> 
> Please let me know if this helps!

I will try this and let you know!

**Comment by icarito** [comment]
Also, note that I have a pull request open to handle the xml:base case but I think it can be improved because I also ran into directories in the manifest and didn't handle them very gracefully (I should've used `os.path.isdir` but hadn't located the temp dir).
https://github.com/learningequality/imscp/pull/8

**Comment by icarito** [comment]
Just a note that this specific issue would be solved by merging https://github.com/learningequality/imscp/pull/8 - I've removed the special handling of directory resources to facilitate merging the PR.

**Comment by icarito** [comment]
> `make_topic_tree_with_entrypoints`



> @icarito I plan on looking into this, but one thing that I'm wondering about is that the temp path doesn't have the SCORM subdirectory in it.
> 
> One other thing that might be worth trying is a different approach we've used for some SCORM content. We basically have a separate topic tree creation function in the imscp library called `make_topic_tree_with_entrypoints` that leaves the SCORM zip unmodified, but creates special endpoints that redirect to various tree items in the zip. You can see the function here:
> 
> https://github.com/learningequality/imscp/blob/cfbf165a2af009d0ce387737224696aa7d57b2a6/src/imscp/ricecooker_utils.py#L66
> 
> If you use this, I think it should avoid any issues with files missing from the end result. In addition to the args taken by `make_topic_tree`, you need to pass the path of the SCORM zip into the function, as well as set `temp_dir` (you can use `tempfile.tempdir` if you don't have a temp dir to set it to).
> 
> Please let me know if this helps!

Hi Kevin,
I've modified educalab_chef.py to use the `make_topic_tree_with_entrypoints` function and given it a reference to the zipfile and a new tempdir. This seems to work fine, in that it successfully uploads the channel, but when trying to preview it, it seems to have trouble with locating the URL for the zipfile:
![imagen](https://user-images.githubusercontent.com/199755/100011568-ab844b00-2db0-11eb-98fd-9dd4ae9800ce.png)

I've been wanting to inspect the temporary files that `imscp` library creates, but they seem to get deleted right away. How could I inspect things to try to better understand what is wrong?
Thanks in advance!

**Comment by icarito** [comment]
Also here's the created channel: https://studio.learningequality.org/channels/871af9eb314352e3a3aa8ace2d1e253e/staging/91ee7aa/e4ccbfe

**Comment by icarito** [comment]
I noticed that the proper URL actually is referenced here:
https://studio.learningequality.org/zipcontent/501ef9fa5220535a823849cdf6e9b224.zip/maac5vmhT-scorm-Cilindro-para-curso-GeoGebra.html

I found this by copying the zip hash from `imscp`'s output.

This feels closer to the desired result, but still the content isn't loading correctly even directly to this URL. Any more pointers would be appreciated!

**Comment by icarito** [comment]
Also, in the specific case of importing the GeoGebra SCORM zip, I find that at this point another likely issue will be the iframe policies at `studio.learningequality.org` since this SCORM package references an external javascript library:
![imagen](https://user-images.githubusercontent.com/199755/100015012-09676180-2db6-11eb-8350-dc503d3e2b98.png)

**Comment by icarito** [comment]
Thanks for your efforts in guiding me.
I'm understanding more and more that I will need to write a Sushi Chef (the terminology was obscure to me, Chef is also a configuration management tool)...
I managed to import a GeoGebra item that was marked as SCORM-ready: https://studio.learningequality.org/zipcontent/2b49248a9f57d1541124639dbfee72a7.zip/mz8xdmhbz-scorm-SCORM-Test-Bruchrechnung-alle-4-Operationen.html but 

However this was uploaded by my modified example script that uses the `make_topic_tree_with_entrypoints` function, it works, but keeps referencing the wrong zip file, "eventos.zip" instead of 2b49248a9f57d1541124639dbfee72a7.zip - how should I indicate to kolibri studio the correct zip file name? Thanks in advance!
https://studio.learningequality.org/channels/871af9eb314352e3a3aa8ace2d1e253e/staging/871af9e

**Comment by kollivier** [comment]
@icarito Ah, sorry, I forgot that the `make_topic_tree_with_entrypoints` expects the file name of the zip passed in to be that of the md5 hash of the file's contents (`2b49248a9f57d1541124639dbfee72a7` is the md5 hash of the contents of `eventos.zip`). You can see the code I use here:

https://github.com/learningequality/sushi-chef-profuturo/blob/6a8c848eb3ad56b22aef21e1f5f12803a9c454da/profuturo/chef.py#L176

Arguably, we should just add that code into `make_topic_tree_with_entrypoints` itself. 

Regarding the external JS library, it's just a library for analytics so it's okay. Kolibri will report an error but the content will load and run fine. 

We are aware that the terminology can be confusing, BTW, and are working towards coming up with clearer terms for our process. However, the sushi chef term is all over the code, so it will be a while before we can fully transition!

**Comment by icarito** [comment]
@kollivier thanks for your prompt and clear response!

> @icarito Ah, sorry, I forgot that the `make_topic_tree_with_entrypoints` expects the file name of the zip passed in to be that of the md5 hash of the file's contents (`2b49248a9f57d1541124639dbfee72a7` is the md5 hash of the contents of `eventos.zip`). You can see the code I use here:
> 
> https://github.com/learningequality/sushi-chef-profuturo/blob/6a8c848eb3ad56b22aef21e1f5f12803a9c454da/profuturo/chef.py#L176

That's very clear and helpful.

> 
> Arguably, we should just add that code into `make_topic_tree_with_entrypoints` itself.

I could try to offer a PR for that!
> 
> Regarding the external JS library, it's just a library for analytics so it's okay. Kolibri will report an error but the content will load and run fine.

Thanks for clarifying that to me!
> 
> We are aware that the terminology can be confusing, BTW, and are working towards coming up with clearer terms for our process. However, the sushi chef term is all over the code, so it will be a while before we can fully transition!

I'm slowly getting more familiar with it! Looking forward to collaborating with you more.

**Comment by icarito** [comment]
I did a simple test and renamed eventos.zip to the md5sum of the contents, and published / deployed a channel with this, but I'm getting:

```
Uncaught DOMException: Permission denied to access property "API_1484_11" on cross-origin object
```
This makes the HTML5 app fail to start. 
However when I open the iframe src in a new tab, the contents displays fine. This sees to be some kind of cross-origin permission on the Iframe tag...

Thanks for your guidance and suggestions!

**Comment by icarito** [comment]
My test is at https://studio.learningequality.org/channels/871af9eb314352e3a3aa8ace2d1e253e/edit/91ee7aa/e4ccbfe

**Comment by kollivier** [comment]
@icarito It is because we use sandboxed iframes in Kolibri and Studio to prevent content from changing the host Kolibri or Studio in any way. In Kolibri, we have a library called Hashi that replicates certain APIs like SCORM and localStorage so that HTML5 apps can still use these features (but it saves the data in user-specific storage). We haven't yet ported this to Studio, though, so when the HTML5 app goes searching the parent for the SCORM API object, it gets permission errors.

If you publish this content and then import it into Kolibri 0.14+ using the token, then you shouldn't get this error.

**Comment by icarito** [comment]
Oh thanks @kollivier I feel I'm getting closer then!

**Comment by icarito** [comment]
> @icarito It is because we use sandboxed iframes in Kolibri and Studio to prevent content from changing the host Kolibri or Studio in any way. In Kolibri, we have a library called Hashi that replicates certain APIs like SCORM and localStorage so that HTML5 apps can still use these features (but it saves the data in user-specific storage). We haven't yet ported this to Studio, though, so when the HTML5 app goes searching the parent for the SCORM API object, it gets permission errors.
> 
> If you publish this content and then import it into Kolibri 0.14+ using the token, then you shouldn't get this error.

Hi @kollivier - I've gotten around to creating the channel to Studio with my [sushi-chef script](https://github.com/icarito/sushi-chef-geogebra).

It interactively asks for a channel Title and Description, but I guess I need to tweak how it decides the Topic.

I've tried importing the channel into Kolibri 0.14.5 but I still get the following error when displaying the content in the iframe (also using the fullscreen version of it):
```
Uncaught DOMException: Permission denied to access property "API_1484_11" on cross-origin object
```

If I choose to open the frame in a new tab, I can see the content successfully, like in Studio.
Please advise.

Also maybe these comments are off topic for this issue, let me know if we should move this conversation to the forum or open a new, related issue.
Thanks in advance.

**Comment by kollivier** [comment]
@icarito Sorry for the late reply! Could you send a link to the Studio channel you're seeing this with? I think the question is if the GeoGebra content requires the `API_1484_11` API to work, or if it is checking whether or not it exists, but it can't check the parent because of permission issues. The latter has a somewhat easy fix, the former would require us to improve our SCORM support.

**Comment by icarito** [comment]
Hi @kollivier thanks for your answer!
Here's a link to a content that works when working outside the iframe, but fails with the above error when inside the Studio iframe:

https://studio.learningequality.org/channels/de932aff604b570b8c5c61037c88c319/view/15dcece/c29d589

**Comment by icarito** [comment]
On importing this very same content to Kolibri Server, I get the same result, works when outside the Iframe, but fails inside it with a cross-origin permission error (I find it strange, because it is the same origin...)

**Comment by icarito** [comment]
@kollivier I did a very small test on the above link, just in my browser: I removed the `sandbox="allow-scripts"` part of the iframe declaration, and reloaded the frame, and the embedded content loaded fine. I guess we either trust the iframe or tune the sandbox to offer access to the API... Hope it helps!

**Comment by icarito** [comment]
@kollivier I've made a PR with the change required on Studio to make this work: https://github.com/learningequality/studio/pull/2666 - please review. I guess the same needs to be done to Kolibri Server, if this is the way to go.

**Comment by kollivier** [comment]
Ah, okay, so it is the origin permissions issue. As Richard noted in the Studio PR, 0.15 has a fix for this, but you can also get this to work in 0.14 by changing your sandbox settings via `options.ini`. Specifically, adding this to it:

```
[HTML5] 
SANDBOX = allow-scripts allow-same-origin 
```

As Richard said, this poses a potential security vulnerability, but if you use only channels in the Kolibri content library plus content from sources you trust, then this should be okay to apply.
