### ISSUE TITLE
Matplotlib Dependency Error

### ISSUE THREAD

**Issue by bp102412** [learningequality/ricecooker#325]
* ricecooker version:
* Python version: 3.8.1
* Operating System: Windows x64

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did
I attempted pip install ricecooker 
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
Collecting matplotlib==2.2.3
  Using cached matplotlib-2.2.3.tar.gz (36.8 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\15707\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\15707\\AppData\\Local\\Temp\\pip-install-f0d_au4_\\matplotlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\15707\\AppData\\Local\\Temp\\pip-install-f0d_au4_\\matplotlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\15707\AppData\Local\Temp\pip-pip-egg-info-10jj61l4'
         cwd: C:\Users\15707\AppData\Local\Temp\pip-install-f0d_au4_\matplotlib\
    Complete output (61 lines):
    ============================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
                matplotlib: yes [2.2.3]
                    python: yes [3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019,
                            23:11:46) [MSC v.1916 64 bit (AMD64)]]
                  platform: yes [win32]

    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.18.4]
          install_requires: yes [handled by setuptools]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype
                            (freetype2\ft2build.h) could not be found.  You may
                            need to install the development package.]
                       png: no  [The C/C++ header for png (png.h) could not be
                            found.  You may need to install the development
                            package.]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]

    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]

    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: no  [PySide2 not found; PyQt5 not found]
                    qt4agg: no  [PySide not found; PyQt4 not found]
                   gtk3agg: no  [Requires pygobject to be installed.]
                 gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                    gtkagg: no  [Requires pygtk]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: no  [cairocffi or pycairo not found]
                 windowing: yes [installing]

    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: no
                     latex: no
                   pdftops: no

    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]

    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png
                            * Please check http://gnuwin32.sourceforge.net/packa
                            * ges/freetype.htm for instructions to install
                            * freetype
                            * Please check http://gnuwin32.sourceforge.net/packa
                            * ges/libpng.htm for instructions to install png
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by rtibbles** [comment]
Thanks for the report @bp102412 - this seems to be a common issue when installing on Windows, I think the best solution is to drop the dependency on more complex packages such as numpy and matplotlib.

**Comment by bp102412** [comment]
@rtibbles I ended up solving the issue by using Python 3.7. We aren’t quite sure what the issue with Python 3.8 was, but everything began working normal after we made the change. Thanks.

**Comment by rtibbles** [comment]
Thanks for the update @bp102412 - I've had similar issues even after downgrading to Python 3.7, so I'll push ahead with the changes in the linked PR that drop the dependency.
