### ISSUE TITLE
Add node class for channel-based quizzes

### ISSUE THREAD

**Issue by sairina** [learningequality/ricecooker#342]
This should be a descendant of the `ExerciseNode` class, but with the addition that the `modality` in the `options` key of `extra_fields` should be set to `QUIZ`.

The implementation should be similar to the CustomNavigationNode implementation that sets another modality:
https://github.com/learningequality/ricecooker/blob/develop/ricecooker/classes/nodes.py#L1075

**Comment by rtibbles** [comment]
Fixed in #349
