### ISSUE TITLE
Fix broken tests on develop

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ricecooker#360]
Currently tests are failing on all platforms on develop, we should do the following:

- [x] Detail which tests are failing and why
- [ ] For each test, verify if it is an issue with the test, or an issue with the functionality being tested
- [ ] Resolve the test issue or functionality issue

**Comment by AtKristijan** [comment]
tests/test_exercises.py::test_exercise_graphie_filename
`E       AssertionError: wrong filename for _ExerciseGraphieFile
E       assert 'ee76848822bf...078b6.graphie' == 'ea2269bb5cf4...6fbc7.graphie'
E         - ea2269bb5cf487f8d883144b9c06fbc7.graphie
E         + ee76848822bf710e037999e9148078b6.graphie
`

tests/test_files.py::test_convertible_substitles_ar_ttml
`E       AssertionError: conferted filename must exit
E       assert None`

tests/test_files.py::test_convertible_substitles_noext_subtitlesformat
`E       AssertionError: conferted filename must exit
E       assert None`

tests/test_thumbnails.py::TestThumbnailGeneration::test_generate_thumbnail_from_pdf
`E       AssertionError: expected two filenames
E       assert 1 == 2
E        +  where 1 = len(['b976c31a7ab68a97f12541d661245238.pdf'])
`

tests/media_utils/test_thumbnails.py::Test_pdf_thumbnail_generation::test_generates_thumbnail
`E   FileNotFoundError: [WinError 2] The system cannot find the file specified`

tests/media_utils/test_thumbnails.py::Test_pdf_thumbnail_generation::test_generates_16_9_thumbnail
`E           ricecooker.utils.images.ThumbnailGenerationError: Fail on PDF C:\projects\learning_equallity\ricecooker\tests\media_utils\files\generate_thumbnail\sampl
e.pdf Unable to get page count. Is poppler installed and in PATH?
`

Detailed errors from running the tests

**Comment by AtKristijan** [comment]
test_exercise_graphie_filename

function `process_file` is failing because `generate_graphie_file` can not find the path for the file "tests/testcontent/exercises/eb3f3bf7c317408ee90995b5bcf4f3a59606aedd"
The file is found if we use "testcontent/exercises/eb3f3bf7c317408ee90995b5bcf4f3a59606aedd"

`@pytest.fixture
def exercise_graphie_filename():
    return "ea2269bb5cf487f8d883144b9c06fbc7.graphie"
`
This is wrong its not returning this graphie
`Expected :ea2269bb5cf487f8d883144b9c06fbc7.graphie
Actual   :ee76848822bf710e037999e9148078b6.graphie
`

**Comment by AtKristijan** [comment]
This is for test test_convertible_substitles_ar_ttml

files.py > write_and_get_hash > return > File failed to write (corrupted).
Also the path need to be fixed we dont need to use `//test/`
