### ISSUE TITLE
Set default value for `TreeNode.learning_activities` when not set explicitly

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/ricecooker#451]
## Observed behavior

A `TreeNode` can be shipped off to Studio without a value in `learning_activities` which has been handled in Kolibri  with [`kolibri/core/content/constants/kind_to_learningactivity.py`
](https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/core/content/constants/kind_to_learningactivity.py) but is not done in Studio. 

## Expected behavior

When a `TreeNode` is created without a value in `learning_activities` we should be setting a default if it is empty. 

## Acceptance criteria

- [ ] Identify the ideal place to define the mapping linked above.
- [ ] Utilize that mapping to ensure that when a `TreeNode` is created that we set the default value into the `learning_activities` array based on that node's kind. **But only if we aren't given a value for `learning_activities` to begin with.**

**Comment by nick2432** [comment]
hey @rtibbles  I want to work on this because I am considering participating in GSoC, and I am thinking of working on the idea 'Integrate Flash resources into the Kolibri ecosystem.' For this, I need to understand the environment of Ricecooker.

**Comment by rtibbles** [comment]
Hi @nick2432 - sure! I'll assign you.

**Comment by Wck-iipi** [comment]
@nick2432 Are you still working on this issue? If not I would like to try to solve this issue

**Comment by rtibbles** [comment]
@nick2432 any progress here?

**Comment by Wck-iipi** [comment]
@rtibbles Should I start working on it?

**Comment by rtibbles** [comment]
Yes, I'll reassign. @nick2432, @Wck-iipi is going to pick this up!
