### ISSUE TITLE
502 Bad Gateway for url: https://contentworkshop.learningequality.org/api/internal/file_diff

### ISSUE THREAD

**Issue by yogeshmhaskule** [learningequality/ricecooker#68]
* ricecooker version:0.5.4
* Python version:3.5.2
* Operating System:MAC  OS X EI Capitan

### Description
I am trying to update magogenie channel on content curation server. While uploading magogenie content using ricecooker, the api "https://contentworkshop.learningequality.org/api/internal/file_diff"
fails 502 bad gateway.
The ricecooker successfully downloads all the contents, while checking the file_diff it gives 502 bad gateway.
Below is the attached screenshot for stack-trace.
![screen shot 2017-04-14 at 3 56 07 pm](https://cloud.githubusercontent.com/assets/7850420/25089737/1ca61f10-239d-11e7-9f65-87555175e0f5.png)

**Comment by yogeshmhaskule** [comment]
We were able to execute the script and proceed further. This issue seems to be resolved.

**Comment by indirectlylit** [comment]
thanks. Please re-open if you encounter it again.
