### ISSUE TITLE
Passing "tags" as parameter for topic node, content node and exercise node(Query).

### ISSUE THREAD

**Issue by yogeshmhaskule** [learningequality/ricecooker#71]
* ricecooker version:0.5.4
* Python version:3.5.2
* Operating System:MAC OS X EI Capitan

### Query
In content curation server we can enter "tags" to content node using UI. 
Is there way to pass tags as parameter through ricecooker. If yes, let us know how we can achieve this.

**Comment by jayoshih** [comment]
Added!
