### ISSUE TITLE
Make Python 2 explicitely disallowed

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ricecooker#92]
### Description

People are spending time running Ricecooker in Python 2, which doesn't work, and then they have strange errors. Recall that both `pip` and `python` commands default to 2.7 on most systems, so it's very easy to fall into this trap.

Python 2.7 is not in the tox.ini matrix anyways.

We should throw a `RuntimeError("Cannot run this in Python 2")` in `ricecooker/__init__.py`

Previous discussion on it here:

https://github.com/learningequality/ricecooker/issues/5#issuecomment-250831114

Is there any compelling reason that Ricecooker should support Python 2.7 ?

**Comment by ivanistheone** [comment]
This was fixed in https://github.com/learningequality/ricecooker/commit/9bce7759b770b50ebb36bf0b8b7bcc974038f615
